const config = {
  site_name: "YOUTUBEMP3",
  site_url: "http://localhost/", // with trailing slash
  allowed_domain: "https://v4.mp3youtube.cc/",
  current_version: "1s",
  splitter: "-",
  lang: [
    "en",
    "fr",
    "de",
    "ar",
    "es",
    "hi",
    "id",
    "it",
    "ja",
    "nl",
    "pt",
    "ru",
    "th",
    "th",
    "tr",
    "vi",
    "zh",
  ],
  lang_name: [
    "English",
    "French",
    "German",
    "Arabic",
    "Spanish",
    "Hindi",
    "Indonesian",
    "Italian",
    "Japanese",
    "Dutch",
    "Portuguese",
    "Russian",
    "Thai",
    "Turkish",
    "Vietnamese",
    "Chinese",
  ],
  flags_name_prefix: [
    "gb",
    "fr",
    "de",
    "sa",
    "es",
    "in",
    "id",
    "it",
    "jp",
    "nl",
    "pt",
    "ru",
    "th",
    "tr",
    "vn",
    "cn",
  ],
  maintainence_mode: false,
  announcement: {
    status: false,
    message: "Happy New Year Everyone!",
  },
  google_tag_id: "GTM-T3RRP64C",
};
module.exports = config;
